### ISSUE TITLE
Используй тернарник

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/range-slider#13]

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-17 09-33-58](https://user-images.githubusercontent.com/31854808/65006786-4e7c4200-d92e-11e9-820a-fb1723ea5f69.png)

**Comment by madnessJs** [comment]
Мне кажется с if'ом наглядей
Вот тут да, наглядней будет тернарник
![image](https://user-images.githubusercontent.com/46949445/66294188-1050bd80-e8f1-11e9-9269-907612c0825d.png)
А тут думаешь тернарник нагляднее?
![image](https://user-images.githubusercontent.com/46949445/66294225-265e7e00-e8f1-11e9-9c5f-d0fbcb86675a.png)
```
parameters.to = parseFloat(parameters.to);
parameters.to = Number.isNaN(parameters.to) ? parameters.max : parameters.to;

```

**Comment by madnessJs** [comment]
Вынес проверки, в которых больше 1 условия, в переменные
