### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/range-slider#2]
Одно из требований на риззоме к заданию использовать  typescript

**Comment by madnessJs** [comment]
> Одно из требований на риззоме к заданию использовать typescript

По началу его необязательно было использовать и я сделал без него. Я у Сергея спрашивал, он сказал если больше половины сделал, то оставить так.
И я пока ушел в рефакторинг, рановато код немного выложил) Вы пока делайте issues все равно, я их закрою чуть позже.

**Comment by GoodDayTodayOkey** [comment]
Хорошо, если Сергей согласовал можно оставить так.

**Comment by madnessJs** [comment]
> Хорошо, если Сергей согласовал можно оставить так.

И еще скажите пожалуйста. Issue закрывать после того как я сделал коммит с исправлением или как?
