### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/range-slider#4]
У тебя счас tip закрывают текст можешь плиз опустить слайдер, и по заданию указано рядом с каждым слайдером разместить панель конфигурирования, чтобы можно было на лету менять параметры(у тебя сейчас для этого приходится нажимать кнопку apply changes).

**Comment by GoodDayTodayOkey** [comment]
Выравнивание и отступ
![Снимок экрана от 2019-09-05 15-23-25](https://user-images.githubusercontent.com/31854808/64324782-308b1500-cff1-11e9-9ba2-beef30772a58.png)

**Comment by madnessJs** [comment]
> Выравнивание и отступ
> ![Снимок экрана от 2019-09-05 15-23-25](https://user-images.githubusercontent.com/31854808/64324782-308b1500-cff1-11e9-9ba2-beef30772a58.png)

Обновил демо страницу со слайдерами

**Comment by GoodDayTodayOkey** [comment]
Не забывай о респонсив. Тут можно просто добавить контейнеру flex-wrap: wrap. В дальнейшем, чтобы не затягивать проверку просьба привязывать коммит к ишью. (добавляй в в именование коммита номер ишью => #4 )
![Снимок экрана от 2019-09-09 10-34-25](https://user-images.githubusercontent.com/31854808/64502070-51ec4980-d2ee-11e9-9ec7-47f78f7fb6a4.png)
