### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/range-slider#6]
Класс  EventEmitter: тут необходимо подправить следующие вещи:
метод on  ничего не говорит о его функциональности, стоит переименовать его в subscribe, emit в notify, добавить метод для отписки unsubscribe. Код перестанет работать если несколько подписчиков подпишутся на одно и тоже событие. Предусмотреть под  этот класс отдельный файл. 
Класс Controller: Сейчас у тебя в контроллере находится логика по вычислению позиции бегунка, значения tip, хотя это зона ответственности модели, также знает о ДОМе, хотя такого не должно быть (например вьюха может быть реализована в консоли, и отсутсвует глобальный объект window).
Класс View: У тебя сейчас инпут который предназначен визуализации значений правого и левого значения бегунка, используется внутри вьюхи слайдера, хотя вьюха о нем ничего не должна о нем знать. Поскольку это вспомгательный слой для отображения, и в повседневном использовании его не должно быть, к тому же размываются края зоны ответственности Вьюхи слайдера.
Класс Model: Сейчас у тебя модель используется только для хранения параметров, хотя должна реализовывать логику вычисления положений бегунка в относительных значениях, которые Вьюха слайдера будет преобразовывать в значения px, а также методы для подписок и оповещений контроллера.

**Comment by madnessJs** [comment]
> Класс EventEmitter: тут необходимо подправить следующие вещи:
> метод on ничего не говорит о его функциональности, стоит переименовать его в subscribe, emit в notify, добавить метод для отписки unsubscribe. Код перестанет работать если несколько подписчиков подпишутся на одно и тоже событие. Предусмотреть под этот класс отдельный файл.
> Класс Controller: Сейчас у тебя в контроллере находится логика по вычислению позиции бегунка, значения tip, хотя это зона ответственности модели, также знает о ДОМе, хотя такого не должно быть (например вьюха может быть реализована в консоли, и отсутсвует глобальный объект window).
> Класс View: У тебя сейчас инпут который предназначен визуализации значений правого и левого значения бегунка, используется внутри вьюхи слайдера, хотя вьюха о нем ничего не должна о нем знать. Поскольку это вспомгательный слой для отображения, и в повседневном использовании его не должно быть, к тому же размываются края зоны ответственности Вьюхи слайдера.
> Класс Model: Сейчас у тебя модель используется только для хранения параметров, хотя должна реализовывать логику вычисления положений бегунка в относительных значениях, которые Вьюха слайдера будет преобразовывать в значения px, а также методы для подписок и оповещений контроллера.

Обновил архитектуру проекта. Неправильно назвал сначала паттерн проектирования, он у меня - MVP. Просмотри пожалуйста свой комментарий на предмет ненужных исправлений в соответствии с изменение паттерна.

**Comment by GoodDayTodayOkey** [comment]
Тут все остается как есть, я описывал тебе необходимые исправления с учетом архитектуры MVP.

**Comment by madnessJs** [comment]
Т.е. 
- Presenter связывает View и Model и подписывается на их изменения
- View у нас main, который в себе заключает вид слайдера и вид инпута. Ничего не знает ни о ком
- Model хранит значения и бизнес логику. Ничего не знает ни о ком
Правильно?

**Comment by GoodDayTodayOkey** [comment]
Нет, в проекте должно быть минимум две вьюхи - одна для отображения слайдера вторая для инпутов, ни одна из них не знает о друг друге. Контроллер подписывается на изменения от обоих, но вьюху слайдера он инициализирует внутри себя, а инстанс вьюхи с инпутами можно например опционально передаваться внутрь слайдера, и разруливать подписку и оповещения между приложением и вьюхой, либо еще как вариант использовать триггеры и возвращать из слайдера методы для оповещения контроллера.

**Comment by GoodDayTodayOkey** [comment]
У тебя сейчас презинтер содержит запускает методы проверки модели, хотя по факту по факту у модели должно остаться лишь два публичных метода, dispatchState(для обновления стэйта) и getState(для получения состояние), а также методы отнаследованные от EventEmitter для подписки(subscribe) и оповещения(notify).

**Comment by GoodDayTodayOkey** [comment]
Модель не должна вызывать сторонние методы, она служит лишь для хранения и расчета нового состояния) 
![Screenshot 2019-10-16 at 10 33 27](https://user-images.githubusercontent.com/31854808/66886116-8693a500-f000-11e9-81bf-7f5e353c26ef.png)

**Comment by GoodDayTodayOkey** [comment]
Поскольку она всегда будет возвращать новый отвалидировнный стэйт, этот метод нудно побить более мелки методы котороые будут валидировать отдельные значения стэйта 
![Screenshot 2019-10-16 at 10 35 28](https://user-images.githubusercontent.com/31854808/66886281-0ae62800-f001-11e9-8407-2f4c75f6fc59.png)

**Comment by GoodDayTodayOkey** [comment]
Удали лишние проверки, у тебя же в слайдере задаются дефолтные параметры.
![Screenshot 2019-10-16 at 10 42 20](https://user-images.githubusercontent.com/31854808/66886571-fc4c4080-f001-11e9-8741-22454d983172.png)

**Comment by madnessJs** [comment]
> Удали лишние проверки, у тебя же в слайдере задаются дефолтные параметры.
> ![Screenshot 2019-10-16 at 10 42 20](https://user-images.githubusercontent.com/31854808/66886571-fc4c4080-f001-11e9-8741-22454d983172.png)

Ну как же. Если пользователь задаст тему как 'tema' или isVertical = 'da' ?

**Comment by madnessJs** [comment]
> > Удали лишние проверки, у тебя же в слайдере задаются дефолтные параметры.
> > ![Screenshot 2019-10-16 at 10 42 20](https://user-images.githubusercontent.com/31854808/66886571-fc4c4080-f001-11e9-8741-22454d983172.png)
> 
> Ну как же. Если пользователь задаст тему как 'tema' или isVertical = 'da' ?
p.s

**Comment by GoodDayTodayOkey** [comment]
> Ну как же. Если пользователь задаст тему как 'tema' или isVertical = 'da' ?
А как они могут быть такими если у тебя в форме радио инпут? И для чего нужны эти проверки?

**Comment by madnessJs** [comment]
> > Ну как же. Если пользователь задаст тему как 'tema' или isVertical = 'da' ?
> 
> А как они могут быть такими если у тебя в форме радио инпут? И для чего нужны эти проверки?

Он может задать из js ведь. Публичным методом update

**Comment by GoodDayTodayOkey** [comment]
Хорошо, тогда эту проверку все равно можно оформить посредством тернарника)
