### ISSUE TITLE
Шаблонизаторы

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/range-slider#7]
Используй шаблонизаторы для верстки
![Снимок экрана от 2019-09-06 12-34-26](https://user-images.githubusercontent.com/31854808/64403433-c2068f80-d0a2-11e9-91c4-089e5f2b4fb9.png)
https://habr.com/ru/post/219873/

**Comment by GoodDayTodayOkey** [comment]
Неверное именование модификаторов 
![Screenshot 2019-10-14 at 10 53 51](https://user-images.githubusercontent.com/31854808/66728737-fa9f4300-ee70-11e9-80bd-479b857b12f8.png)

**Comment by madnessJs** [comment]
> Неверное именование модификаторов
> ![Screenshot 2019-10-14 at 10 53 51](https://user-images.githubusercontent.com/31854808/66728737-fa9f4300-ee70-11e9-80bd-479b857b12f8.png)

Еще тут 675b8a731b7f39786664f6571baf1dbe82938d4a исправил
